steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/golden-manifest-237210/mall-account:$REVISION_ID', '.'] 
  dir: 'mall-account'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/golden-manifest-237210/mall-account:$REVISION_ID'] 
  dir: 'mall-account'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/mall-account'
  - 'n=mall'
  - 'mall-account=gcr.io/golden-manifest-237210/mall-account:$REVISION_ID'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'